spring:
  application:
    name: task-management-system
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
jwt-secret: ${JWT_SECRET}